---
title: "Descriptives and Exploratory Analysis"
author: "Kristen Fedak"
date: "11/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
```

# Participant info

```{r}
participants <- read_rds("output_files/participants.rds") %>%
  mutate_if(is.factor, tolower)
```

```{r}
table_data_sex <- participants %>%
  select(age_months, bmi_pct, height_cm, weight_kg, age_years, sex) %>%
  pivot_longer(cols = -sex, names_to = "var", values_to = "val") %>%
  group_by(var, sex) %>%
  summarise(mean = mean(val, na.rm = TRUE),
            n = n(),
            sd = sd(val, na.rm = TRUE),
            min = min(val, na.rm = TRUE),
            max = max(val, na.rm = TRUE))

table_data_total <- participants %>%
  select(age_months, bmi_pct, height_cm, weight_kg, age_years) %>%
  pivot_longer(cols = everything(), names_to = "var", values_to = "val") %>%
  group_by(var) %>%
  summarise(mean = mean(val, na.rm = TRUE),
            n = n(),
            sd = sd(val, na.rm = TRUE),
            min = min(val, na.rm = TRUE),
            max = max(val, na.rm = TRUE)) %>%
  mutate(sex = "total") %>%
  bind_rows(table_data_sex) %>%
  arrange(var, desc(sex)) %>%
  select(var, sex, n, mean, sd, min, max)
```

```{r}
table_data_cat <- participants %>%
  select(sex, bmi_cat, race_cat, smoke_live, smoke_around, smoke_current, asthma_ever) %>%
  pivot_longer(cols = everything(), names_to = "cat", values_to = "val") %>%
  group_by(cat, val) %>%
  count() %>%
  mutate(percent = ((n/299)*100))
```

### Participant age, height, weight, and BMI percentage

* by gender

```{r}
kable(table_data_total, digits = 0) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F) %>%
  row_spec(row = seq(1,15,3), bold = T) %>%
  row_spec(row = 0, font_size = 14, bold = T) %>%
  collapse_rows(columns = 1, valign = "middle")
```

### Participant asthma, BMI category, race/ethnicity, gender, and smoking status

```{r}
kable(table_data_cat, digits = 0) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F) %>%
  row_spec(row = 0, font_size = 14, bold = T) %>%
  collapse_rows(columns = 1, valign = "middle")
```


## Lung Function

```{r}
lf_pre <- read_rds("output_files/pre_bronchodilator_lf.rds") %>%
  mutate_if(is.character, tolower) %>%
  mutate(num_trials = as.numeric(numpretrials),
         accept = preacc,
         test = "pre-bronchodilator") %>%
  select(-numpretrials)

lf_post <- read_rds("output_files/post_bronchodilator_lf.rds") %>%
  mutate_if(is.character, tolower) %>%
  mutate(num_trials = as.numeric(numposttrials),
         accept = postacc,
         test = "post-bronchodilator") %>%
  select(-numposttrials)
```

### Trial Status - number of acceptable trials

```{r}
trial_status <- lf_pre %>% 
  bind_rows(lf_post) %>% 
  filter(var == "fev1", trial_n == 1) %>%
  group_by(test, accept) %>%
  summarize(number = n(),
            avg_n_trials = mean(num_trials)) %>%
  arrange(desc(test), desc(accept))
```

```{r}
kable(trial_status, digits = 1) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F) %>%
  row_spec(row = 0, font_size = 14, bold = T) %>%
  collapse_rows(columns = 1, valign = "middle")
```

### Average Lung Function

#### using best trial (Trial #1)

```{r}
average_lf <- lf_pre %>% 
  bind_rows(lf_post) %>%
  filter(trial_n == 1) %>%
  mutate(var = as.factor(var)) %>%
  filter(var == "fvc" | var== "fev1" | var == "fev1fvc" | var == "fef2575") %>%
  group_by(test, accept, var) %>%
  summarize(mean_val = mean(value, na.rm = TRUE),
            sd_val = sd(value, na.rm = TRUE),
            min_val = min(value, na.rm = TRUE),
            max_val = max(value, na.rm = TRUE)) %>%
  arrange(desc(test), desc(accept))
```

```{r}
kable(average_lf, digits = 1) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F) %>%
  row_spec(row = 0, font_size = 14, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```
