---
title: "load data"
author: "Kristen Fedak"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## baseln_n299 data (Participant info, lung function tests)

```{r}
bsln_n299 <- read_csv("../c7baseln_n299_apr2018update.csv",
  na = (c(".N", "N", "NA")),
  col_types = cols(.default = "c")) %>%
  rename_all(tolower)
```

* create participant data

```{r}
participants <- bsln_n299 %>%
  dplyr::select(id, agemon,
                bmi_cat, bmipct, bmi, bmipct95, bmidif95,
                height, weight, gender, age,
                race_cat,
                livew_smok, smokw_child,
                vis_month,
                c7hhb_8, c7sm_2) %>%
  dplyr::rename(age_months = "agemon",
                age_years = "age",
                sex = "gender",
                asthma_ever = "c7hhb_8",
                bmi_pct = "bmipct",
                visit_month = "vis_month",
                smoke_live = "livew_smok", #live with a smoker
                smoke_around = "smokw_child", #people smoke around child in home or car
                smoke_current = "c7sm_2") %>% #current smoker 
  dplyr::mutate(id = as.factor(id),
                bmi_cat = as.factor(bmi_cat),
                sex = as.factor(sex),
                race_cat = as.factor(race_cat),
                smoke_live = as.factor(smoke_live),
                smoke_around = as.factor(smoke_around),
                smoke_current = as.factor(smoke_current),
                asthma_ever = as.factor(asthma_ever),
                visit_month = as.factor(visit_month), 
                age_months = as.numeric(age_months),
                bmi = as.numeric(bmi),
                bmi_pct = as.numeric(bmi_pct),
                bmipct95 = as.numeric(bmipct95),
                bmidif95 = as.numeric(bmidif95),
                height = as.numeric(height),
                weight = as.numeric(weight),
                age_years = as.numeric(age_years))
```

* create lung function data (all, pre-bronchodilator, post-bronchodilator)

```{r}
#all lung function data
lung_function <- bsln_n299 %>%
  dplyr::select(id, 623:734)

#pre-bronchodilator test
pre_lf <- lung_function %>%
  dplyr::select(id, contains("Pre"))

#post-bronchodilator test
post_lf <- lung_function %>%
  dplyr::select(id, contains("Post"))
```

* turn lung function data into long format

```{r}
pre_lf_long <- pre_lf %>%
  dplyr::rename(fev1fvc_pre1 = "pre_fev1fvc") %>%
  pivot_longer(cols = -c("id", "qcgrade_pre", "preacc", "numpretrials"),
               names_to =  "var", values_to = "value") %>%
               mutate(trial_n = var) %>%
               mutate(trial_n = as.numeric(gsub("^.*_pre", "", trial_n)),
                      var = gsub("(.*)_.*", "\\1", var),
                      value = as.numeric(value))

post_lf_long <- post_lf %>%
  dplyr::rename(fev1fvc_post1 = "post_fev1fvc") %>%
  pivot_longer(cols = -c("id", "qcgrade_post", "postacc", "numposttrials"),
               names_to =  "var", values_to = "value") %>%
               mutate(trial_n = var) %>%
               mutate(trial_n = as.numeric(gsub("^.*_post", "", trial_n)),
                      var = gsub("(.*)_.*", "\\1", var),
                      value = as.numeric(value))
```

# Air Pollution Exposure metrics
```{r}
co_yrprior <- read_xlsx("../Yearprior_Exposure/C7_CO_O3_PM_YearPrior_Exposures_2014-2017_17Apr2018_forReleasev2.xlsx",
                              sheet = 2) %>%
              rename_all(tolower) %>%
              dplyr::rename(id = "subject")
```




# Save .RDS files

```{r}
write_rds(participants, "participants.rds")
write_rds(lung_function, "lungfunction_all.rds")
write_rds(pre_lf_long, "pre_bronchodilator_lf.rds")
write_rds(post_lf_long, "post_bronchodilator_lf.rds")
```


